# Rustfmt configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"

# Formatting
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Other
format_macro_matchers = true
format_strings = false
use_field_init_shorthand = true
use_try_shorthand = true
